### ISSUE TITLE
Noob question for clarification

### ISSUE THREAD

**Issue by Darkinuyasha** [teamtnt/tntsearch#105]
Sorry, my question will be very noob, but I can't get on a safe and completeley understandable ground so I'll ask.

What is tntsearch? Is an alternative to laravel scout? To the various full text search program that need a server (and not a shared server like mine) to work (ike ElasticSearch)?

I want to create a nice amazon-like search system. I am in the right place? Or theres more that I need to know? 
There are examples of use that I can see?

More question may come next. Thanks in advance for the help :)

**Comment by stokic** [comment]
TNTSearch is a full text search package. You can read the documentation and get what it does :)

It's not an alternative to Laravel Scout, Scout is just a wrapper and in that essence TNTSearch has a driver for Scout, but scout itself doesn't do any search related stuff.

TNTSearch doesn't need a server and it's not a server, it's a php package that stores all of the data in sqlite database. There are example, and they are mentioned in the readme together with links to tutorials.

Shared server might be a problem because of the initial indexing, but if you can run artisan commands then it's not a problem. Btw you can get a VPS for cheap at [DO](https://camo.githubusercontent.com/8df3afc5d02156065d12975015e1033116485b1f/68747470733a2f2f6b6f69737479612e6769746875622e696f2f66696c65732f6469676974616c2d6f6365616e2d3339337836342e706e67)

**Comment by Darkinuyasha** [comment]
For examples I intended "good search basic codes", not examples to tntSearch alone. And the tutorials are about Laravel, wich I don't use.
I never used php framework before because I never felt the need.

I don't really undestood the last sentence.

**Comment by roballport** [comment]
@Darkinuyasha For the last sentence @stokic is saying that the indexing process (the "index" is the optimised file, which itself is a flat sqlite database) that TNTSearch searches as opposed your application database) to your  is fairly intensive and may be require better hosting. However, I've indexed ~750k records on shared hosting without issue.

TNT Search is not tied to any particular frameowrk and can be used in any PHP project. You see lot's of Laravel related tutorials due to popularity and the ease of use of TNT Search with Scout. This is very easy and everything you need including examples is available at https://github.com/teamtnt/tntsearch

**Comment by nticaric** [comment]
@ultrono the upcoming version will have an option to exclude the primary key from index

**Comment by ultrono** [comment]
@nticaric - absolutely spot on!

**Comment by nticaric** [comment]
@ultrono after thinking a little bit about the primary key, I think it makes more sense to exclude it by default and to include it only if needed. This change has been affected in version 1.2.0

https://github.com/teamtnt/tntsearch#making-the-primary-key-searchable
