### ISSUE TITLE
Get keywords list after a search (fuzzy search)

### ISSUE THREAD

**Issue by rkyoku** [teamtnt/tntsearch#144]
Hi there!

I was thinking it could be great to be given the final list of keywords when performing a fuzzy search (even when not), as another entry of the returned array.

For example, I'm searching for "_examlpe_", but there is a typo in my search term. TntSearch will retrieve the list of matching keywords when performing the levenshtein, which will be "_example_".

Now, for some reason (#93 attributing weights), we need to perform additional sorting. It would be soooooo useful to have the "corrected" search term at our disposal... :) Right?

Tell me know what you think!

Cheers,

**Comment by nticaric** [comment]
Not sure of the application but there are better ways for catching typos than using fuzziness. A better way for tolerant retrieval are ngrams. I wrote somewhere a tutorial about this.

Fuzziness with the default setting can't fetch if the first letter is misspelled or even the first 3 letters.

Field weighting and boosting isn't supported because most users wouldn't get it right.
