### ISSUE TITLE
Searching with dash "-"

### ISSUE THREAD

**Issue by luisdalmolin** [teamtnt/tntsearch#21]
Hi there, first of all, thank's for this awesome project.

Is there a way to search for dash keywords, like this: `70-200`. My app have a lot products like **Canon 70-200**, and it's not searching correctly.

**Comment by nticaric** [comment]
Glad you like the project. I need to do some refactoring of the package in order to make such things
easier to change. In this particular case, simply a dash needs to be added to the regex in `breakIntoTokens` method in `TNTIndexer`. I'll try to extract this method to a new class `Tokenizer` and make it a dependency of TNTIndexer, so you'll be able to change the `breakIntoTokens` method as you like

**Comment by nticaric** [comment]
Version v0.6.6 brings the feature you need. Here's how you do it. First, create your own Tokenizer class that implements Tokenizer interface:

```php

use TeamTNT\TNTSearch\Support\TokenizerInterface;

class SomeTokenizer implements TokenizerInterface {

    public function tokenize($text) {
        return preg_split("/[^\p{L}\p{N}-]+/u", strtolower($text), -1, PREG_SPLIT_NO_EMPTY);
    }
}
```
The only difference here from the original is that the regex contains a dash `[^\p{L}\p{N}-]`

After you have the tokenizer ready, your `TNTIndexer` and `TNTSearch` class should consume it.

```php
$someTokenizer = new SomeTokenizer;

$indexer = new TNTIndexer;
$indexer->setTokenizer($someTokenizer);
```

And in the `TNTSearch` class you do the same

```php
$someTokenizer = new SomeTokenizer;

$tnt = new TNTSearch;
$tnt->setTokenizer($someTokenizer);
````

The rest stays the same :D

**Comment by luisdalmolin** [comment]
Awesome!

Thank you very much. I will try.
Keep up the good work.

**Comment by ViliusS** [comment]
I'm trying to code a custom search tokenizer for developer manual built on Grav. Most pages in the manual include instructions to functions which include unserscores in their names.

I'm wondering, are the instructions above still up to date? Using setTokenizer($myTokenizer) on indexer works, but when I try to set it on search object my code produces an error:
Call to a member function query() on null
tntsearch/vendor/teamtnt/tntsearch/src/TNTSearch.php:399

I've investigated the code and it seems that setTokenizer signature was changed https://github.com/teamtnt/tntsearch/commit/6eb15ad2d7e4275e8a008a3b85a215419754b6b2 

From what I understand setTokenizer() is only needed for indexer object now, and search automatically will use the required one? Can anyone confirm this?

**Comment by nticaric** [comment]
The instructions have changed a little bit in the meanwhile. What you should do now to use a different tokenizer is to
either set it with `setTokenizer` method on the indexer or simply add the new tokenizer to the config

```php
'tokenizer' => \Namespace\To\Your\CustomTokenizer::class
```

**Comment by ViliusS** [comment]
Can you confirm that this also sets correct tokenizer for selectIndex() and getIndex() methods in TNSSearch.php ? Looking at the code I'm not sure how this is handled, but I get the same error when trying to call any of these methods.
`Call to a member function query() on null`

**Comment by nticaric** [comment]
Please take a look at these two lines:
https://github.com/teamtnt/tntsearch/blob/master/src/TNTSearch.php#L85
and
https://github.com/teamtnt/tntsearch/blob/master/src/TNTSearch.php#L458

If you getting the `Call to a member function query() on null` means you haven't selected the index.

Can you show us the exact code that you're using?

**Comment by ViliusS** [comment]
I've looked at the exactly these two lines but I don't understand how they work. For me, it looks like selectIndex() should be OK, because it gets tokenizer from the internal settings SQLite database, correct?
But getIndex() is a mistery for me, because from what I understand, it sets tokenizer with **TNTSearch constructor**, which is a simple:
` $this->tokenizer = new Tokenizer;`
Isn't this a problem?

The code I'm using is from Grav TNTSearch plugin https://github.com/trilbymedia/grav-plugin-tntsearch/blob/develop/classes/GravTNTSearch.php#L216
I've modified createIndex() on Line 216 by simply adding:
```
$myTokenizer = new myTokenizer;
$indexer->setTokenizer(myTokenizer);
```
("use name\space\to\tokenizer" on the top is also added).

**Comment by nticaric** [comment]
The most likely thing is that you're calling `setTokenizer` before `selectIndex();` and it should be the other way around

```php
use TeamTNT\TNTSearch\TNTSearch;

$tnt = new TNTSearch;

$tnt->loadConfig($config);
$tnt->selectIndex("name.index");

$res = $tnt->search("This is a test search", 12);
```

The tokenizer will be automatically applied because its saved in the index

**Comment by ViliusS** [comment]
I have set tokenizer through the config instead of calling setTokenizer() and so far it works. Thank you!
