### ISSUE TITLE
storage_path on an external server

### ISSUE THREAD

**Issue by mandys** [teamtnt/tntsearch#34]
Hi,

In case of multi server environment, the search can originate form any server ( www1, 2, 3..10 ).

It's not possible to have an index on every box.

How do we solve the issue of having storage_path on an external ( virtual ) server accessible to all ?

Thanks.

**Comment by nticaric** [comment]
The index file is nothing more than a regular SQLite database. Since SQLite isn't a network database but a lat file, it doesn't have any network connection ability built into it. What you could do is store the index on a network-accessible shared drive.

Maybe there is another solution, but I am not aware of it.

**Comment by mandys** [comment]
On Amazon EC2, they offer something called Elastic File System that can be mounted on the EC2 instances. https://aws.amazon.com/efs/

I haven't tried it yet but seems like for bigger indexes that might be the way forward.

Thanks for your help though!

**Comment by nticaric** [comment]
Yeah, that might be the solution if you can access the same filesystem from different instances.
Would be great if you could try it out
