### ISSUE TITLE
fields & hitlist

### ISSUE THREAD

**Issue by fishgrind** [teamtnt/tntsearch#56]
Hey,

What are the fields table and hitlist table for in the database, they remain empty.

Also is there a way to save a title in the database so the search results have a title.

And third and last, my info table is filled with 'TeamTNT\TNTSearch\Stemmer\PorterStemmer' what is this for?

**Comment by nticaric** [comment]
In the current version TNTSearch is field agnostic, which means we don't distinguish a title from a body in a document. The plan is to add field weighting in upcoming versions, therefore some of the tables and code to support this is already included in the package.

TNTSearch returns the id of the document that contains your query, so after you fetch the searched document you can also include the title if the document has it.

The info table holds the stemmer which is used for stemming the words when you do a query.
If you're language was for example german, than the stemmer instead of PorterStemmer would be GermanStemmer

**Comment by fishgrind** [comment]
@nticaric  Thanks for the explanation!

I have played around with it, really cool and simple. I love it!
