### ISSUE TITLE
Fuzzy Searching?

### ISSUE THREAD

**Issue by dragonfire1119** [teamtnt/tntsearch#9]
Do you plan on adding Fuzzy Searching to this awesome project?

**Comment by nticaric** [comment]
Yes, it is planned for the future versions.

**Comment by dragonfire1119** [comment]
Ok cool! Ya fuzzy searching is ten times better for users when there trying to find something & they don't really know all the words. Do you have a Roadmap of the features for public viewing?

**Comment by nticaric** [comment]
Currently not. The package is relatively new so we are trying to collect some feedback first and see what users need most

**Comment by dragonfire1119** [comment]
Well I think you've done a really great job so far.

Just needs:
Updating for indexing instead of having to delete it and start over. #5 
Fuzzy Searching would make it 10 times better. 

Thanks for your time in this project.

**Comment by dragonfire1119** [comment]
@nticaric Thanks for listening to my ideas! Have you thought about creating a trello board?

**Comment by shivaacharjee** [comment]
well..will  be great

On Mon, May 16, 2016 at 8:50 PM, Christopher <notifications@github.com>
wrote:

> @nticaric <https://github.com/nticaric> Thanks for listening to my ideas!
> Have you thought about creating a trello board?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/teamtnt/tntsearch/issues/9#issuecomment-219453534>
>



-- 
Shiva Acharjee
Software Engineer @ NETechno (p) Ltd
http://shivaacharjee.com
Facebook: http://facebook.com/billshiva
Twitter: @shivaacharjee
https://about.me/shivaacharjee

Peace be on you!



***************************************************
This e-mail and any attachments may contain confidential and
privileged information. If you are not the intended recipient,
please notify the sender immediately by return e-mail, delete this
e-mail and destroy any copies. Any dissemination or use of this
information by a person other than the intended recipient is
unauthorized and may be illegal.
***************************************************

**Comment by jgbneatdesign** [comment]
Yeah fuzzy searching would be awesome.

**Comment by xenDE** [comment]
for fuzzy and scoring better use a lucene search engine.

like  https://github.com/nqxcode/laravel-lucene-search

**Comment by nticaric** [comment]
@xenDE this package was created because Zend Lucene wasn't good enough :) BM25 matching algorithm is superior to the VSM (vector space model) which lucene uses for scoring. The package has also support for boolean search which is implemented in the way that it gives control to the user not to the developer. The fuzziness and proximity can be added by extending the search class but it affects performance, like it does to the package you recommended ;) The index can also be easily updated. Access to it is much faster because it uses sqlite extension which is written in C and you can't beat C ;)

**Comment by dragonfire1119** [comment]
@nticaric Is there any news or progress on the fuzzy search?

**Comment by nticaric** [comment]
@dragonfire1119 Yes, the fuzzy search feature has been added in version v0.8.0

```php
use TeamTNT\TNTSearch\TNTSearch;

$tnt = new TNTSearch;

$tnt->loadConfig($config);
$tnt->selectIndex("name.index");
$tnt->fuzziness = true;

//when the fuzziness flag is set to true the keyword juleit will return
//documents that match the word juliet, the default levenshtein distance is 2
$res = $tnt->search("juleit");

```

You can tweak it by changing the TNTSearch member variables

```php

public $fuzzy_prefix_length  = 2;
public $fuzzy_max_expansions = 50;
public $fuzzy_distance       = 2 //represents the levenshtein distance;
```

In order to better understand how the fuzziness implementation works, here's a good read
from the elastic blog :)

https://www.elastic.co/blog/found-fuzzy-search

**Comment by dragonfire1119** [comment]
@nticaric Thanks for your time on the project. How would you set the fuzziness attribute when you use the Facade?

**Comment by nticaric** [comment]
@dragonfire1119 Haven't tried, but this should do the trick

`TNTSearch::getFacadeRoot()->fuzziness = true;`
